### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by infinity-computers-dot-net** [Shinmera/cl-gpio#3]
```
* (gpio:pins)
NIL
```

I am using SBCL 2.0.3 on a Raspberry Pi Model B Rev 1.

**Comment by brandflake11** [comment]
I know this is an old issue, but you may have to export your pins first. I did that by doing this:


```
(ql:quickload "cl-gpio")
(loop for i from 1 to 26
	       do (gpio:export i))
```

Then all of the pins will show up:

```
(gpio:pins) =>
(#<CL-GPIO:PIN 0 :OUT> #<CL-GPIO:PIN 1 :IN> #<CL-GPIO:PIN 10 :IN>
 #<CL-GPIO:PIN 11 :IN> #<CL-GPIO:PIN 12 :IN> #<CL-GPIO:PIN 13 :IN>
 #<CL-GPIO:PIN 14 :IN> #<CL-GPIO:PIN 15 :IN> #<CL-GPIO:PIN 16 :IN>
 #<CL-GPIO:PIN 17 :IN> #<CL-GPIO:PIN 18 :IN> #<CL-GPIO:PIN 19 :IN>
 #<CL-GPIO:PIN 2 :IN> #<CL-GPIO:PIN 20 :IN> #<CL-GPIO:PIN 21 :IN>
 #<CL-GPIO:PIN 22 :IN> #<CL-GPIO:PIN 23 :IN> #<CL-GPIO:PIN 24 :IN>
 #<CL-GPIO:PIN 25 :IN> #<CL-GPIO:PIN 26 :IN> #<CL-GPIO:PIN 3 :IN>
 #<CL-GPIO:PIN 4 :IN> #<CL-GPIO:PIN 5 :IN> #<CL-GPIO:PIN 6 :IN>
 #<CL-GPIO:PIN 7 :IN> #<CL-GPIO:PIN 8 :IN> #<CL-GPIO:PIN 9 :IN>)
```

**Comment by Sod-Almighty** [comment]
Yes, that's what I ended up doing.

But the documentation should make this clear.

**Comment by brandflake11** [comment]
Maybe when I get some time today I can put this in the readme and do a pull request.

**Comment by brandflake11** [comment]
I just submitted a pull request with (hopefully) clearer instructions. I spent a year wondering why I couldn't get this package to work, so hopefully this pull will help new users get up and running on their gpio+common lisp adventures.
